module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx,css}"],
  theme: {
    colors: {
      primary: {
        blue: "#1265AE",
      },
      secondary: {
        "white-1": "#FFFAE9",
        "green-1": "#61B930",
        "blue-1": "#2475BB",
        "blue-2": "#3DA1F6",
        "blue-3": "#A0D3FF",
        "blue-4": "#D8EDFF",
      },
      accent: {
        red: "#FE8668",
        orange: "#FDBC1F",
        teal: "#30D6B0",
        indigo: "#4269F2",
      },
      neutral: {
        black: "#404040",
        "dark-grey": "#BFBFBF",
        "subtle-grey": "#F3F4F8",
        grey: "#C7C9D9",
        "light-grey": "#DFDFDF",
        white: "#F6F9FF",
      },
      warning: {
        "danger-1": "#A70000",
        "danger-2": "#D62727",
        "danger-3": "#FF5252",
        "danger-4": "#FFE4E4",
        "caution-1": "#E69500",
        "caution-2": "#FFB52E",
        "caution-3": "#FFC45C",
        "caution-4": "#FFD68A",
        "safe-1": "#398564",
        "safe-2": "#49AB81",
        "safe-3": "#61CE9F",
        "safe-4": "#B0EADD",
        "action-1": "#2475BB",
        "action-2": "#3DA1F6",
        "action-3": "#A0D3FF",
        "action-4": "#D8EDFF",
      },
    },
    extend: {
      fontSize: {
        h1: "64px",
        h2: "48px",
        h3: "42px",
        h4: "36px",
        h5: "32px",
        h6: "24px",
        h7: "20px",
        s1: "18px",
        s2: "16px",
        s3: "14px",
        s4: "12px",
        p1: "16px",
        p2: "14px",
        p3: "12px",
        p4: "10px",
      },
      fontFamily: {
        inter: ["Inter", "sans - serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
